export const countries = [
  { title: "Україна", value: "UA" },
  { title: "Афганістан", value: "AF" },
  { title: "Албанія", value: "AL" },
  { title: "Алжир", value: "DZ" },
  { title: "Андорра", value: "AD" },
  { title: "Ангілья", value: "AI" },
  { title: "Антарктида", value: "AQ" },
  { title: "Антильські острови", value: "AN" },
  { title: "Аргентина", value: "AR" },
  { title: "Віргінські острови", value: "VG" },
  { title: "Вірменія", value: "AM" },
  { title: "Венесуела", value: "VE" },
  { title: "В'єтнам", value: "VN" },
  { title: "Габон", value: "GA" },
  { title: "Гаїті", value: "HT" },
  { title: "Гамбія", value: "GM" },
  { title: "Гана", value: "GH" },
  { title: "Гватемала", value: "GT" },
  { title: "Гвінея", value: "GN" },
  { title: "Гвінея-Бісау", value: "GW" },
  { title: "Гернсі", value: "GG" },
  { title: "Гренада", value: "GD" },
  { title: "Греція", value: "GR" },
  { title: "Грузія", value: "GE" },
  { title: "Данія", value: "DK" },
  { title: "Демократична Республіка Конго", value: "CD" },
  { title: "Джибуті", value: "DJ" },
  { title: "Домініка", value: "DM" },
  { title: "Домініканська Республіка", value: "DO" },
  { title: "Еквадор", value: "EC" },
  { title: "Естонія", value: "EE" },
  { title: "Есватіні", value: "SZ" },
  { title: "Ефіопія", value: "ET" },
  { title: "Єгипет", value: "EG" },
  { title: "Ємен", value: "YE" },
  { title: "Замбія", value: "ZM" },
  { title: "Західний Сахара", value: "EH" },
  { title: "Зеландія", value: "NZ" },
  { title: "Ізраїль", value: "IL" },
  { title: "Індія", value: "IN" },
  { title: "Індонезія", value: "ID" },
  { title: "Ірландія", value: "IE" },
  { title: "Ісландія", value: "IS" },
  { title: "Іспанія", value: "ES" },
  { title: "Італія", value: "IT" },
  { title: "Йорданія", value: "JO" },
  { title: "Кабо-Верде", value: "CV" },
  { title: "Кайманові острови", value: "KY" },
  { title: "Камбоджа", value: "KH" },
  { title: "Канада", value: "CA" },
  { title: "Катар", value: "QA" },
  { title: "Кенія", value: "KE" },
  { title: "Кіпр", value: "CY" },
  { title: "Кірібаті", value: "KI" },
  { title: "Колумбія", value: "CO" },
  { title: "Коморські острови", value: "KM" },
  { title: "Конго", value: "CG" },
  { title: "Коста-Ріка", value: "CR" },
  { title: "Куба", value: "CU" },
  { title: "Кувейт", value: "KW" },
  { title: "Лаос", value: "LA" },
  { title: "Латвія", value: "LV" },
  { title: "Лесото", value: "LS" },
  { title: "Ліван", value: "LB" },
  { title: "Ліберія", value: "LR" },
  { title: "Лівія", value: "LY" },
  { title: "Литва", value: "LT" },
  { title: "Ліхтенштейн", value: "LI" },
  { title: "Люксембург", value: "LU" },
  { title: "Мавританія", value: "MR" },
  { title: "Маврикій", value: "MU" },
  { title: "Мадагаскар", value: "MG" },
  { title: "Макао", value: "MO" },
  { title: "Малаві", value: "MW" },
  { title: "Малайзія", value: "MY" },
  { title: "Малі", value: "ML" },
  { title: "Мальдіви", value: "MV" },
  { title: "Мальта", value: "MT" },
  { title: "Марокко", value: "MA" },
  { title: "Маріанські острови", value: "MP" },
  { title: "Маршалові острови", value: "MH" },
  { title: "Мексика", value: "MX" },
  { title: "Мікронезія", value: "FM" },
  { title: "Мозамбік", value: "MZ" },
  { title: "Молдова", value: "MD" },
  { title: "Монако", value: "MC" },
  { title: "Монголія", value: "MN" },
  { title: "Монтсеррат", value: "MS" },
  { title: "Намібія", value: "NA" },
  { title: "Непал", value: "NP" },
  { title: "Нігер", value: "NE" },
  { title: "Нігерія", value: "NG" },
  { title: "Нідерланди", value: "NL" },
  { title: "Нікарагуа", value: "NI" },
  { title: "Ніуе", value: "NU" },
  { title: "Нова Каледонія", value: "NC" },
  { title: "Норвегія", value: "NO" },
  { title: "Об'єднані Арабські Емірати", value: "AE" },
  { title: "Оман", value: "OM" },
  { title: "Острів Різдва", value: "CX" },
  { title: "Пакистан", value: "PK" },
  { title: "Палау", value: "PW" },
  { title: "Панама", value: "PA" },
  { title: "Папуа - Нова Гвінея", value: "PG" },
  { title: "Парагвай", value: "PY" },
  { title: "Перу", value: "PE" },
  { title: "Південна Корея", value: "KR" },
  { title: "Південний Судан", value: "SS" },
  { title: "Північна Корея", value: "KP" },
  { title: "Польща", value: "PL" },
  { title: "Португалія", value: "PT" },
  { title: "Руанда", value: "RW" },
  { title: "Румунія", value: "RO" },
  { title: "Реюньйон", value: "RE" },
  { title: "Сальвадор", value: "SV" },
  { title: "Самоа", value: "WS" },
  { title: "Сан-Марино", value: "SM" },
  { title: "Саудівська Аравія", value: "SA" },
  { title: "Сенегал", value: "SN" },
  { title: "Сейшельські острови", value: "SC" },
  { title: "Сент-Барселона", value: "BL" },
  { title: "Сент-Кітс і Невіс", value: "KN" },
  { title: "Сент-Люсія", value: "LC" },
  { title: "Сент-П'єр і Мікелон", value: "PM" },
  { title: "Сербія", value: "RS" },
  { title: "Сингапур", value: "SG" },
  { title: "Сирія", value: "SY" },
  { title: "Словаччина", value: "SK" },
  { title: "Словенія", value: "SI" },
  { title: "Соломонові острови", value: "SB" },
  { title: "Сомалі", value: "SO" },
  { title: "Судан", value: "SD" },
  { title: "Суринам", value: "SR" },
  { title: "США", value: "US" },
  { title: "Таджикистан", value: "TJ" },
  { title: "Таїланд", value: "TH" },
  { title: "Танзанія", value: "TZ" },
  { title: "Того", value: "TG" },
  { title: "Токелау", value: "TK" },
  { title: "Тонга", value: "TO" },
  { title: "Тринідад і Тобаго", value: "TT" },
  { title: "Туніс", value: "TN" },
  { title: "Туркменістан", value: "TM" },
  { title: "Туреччина", value: "TR" },
  { title: "Тувалу", value: "TV" },
  { title: "Уганда", value: "UG" },
  { title: "Узбекистан", value: "UZ" },
  { title: "Уругвай", value: "UY" },
  { title: "Фіджі", value: "FJ" },
  { title: "Філіппіни", value: "PH" },
  { title: "Фінляндія", value: "FI" },
  { title: "Франція", value: "FR" },
  { title: "Хорватія", value: "HR" },
  { title: "Центральноафриканська Республіка", value: "CF" },
  { title: "Чад", value: "TD" },
  { title: "Чехія", value: "CZ" },
  { title: "Чилі", value: "CL" },
  { title: "Швейцарія", value: "CH" },
  { title: "Швеція", value: "SE" },
  { title: "Шпіцберген", value: "SJ" },
  { title: "Шрі-Ланка", value: "LK" },
  { title: "Ямайка", value: "JM" },
  { title: "Японія", value: "JP" },
];

export const SEX_OPTIONS = [
  { value: "male", title: "Чоловік" },
  { value: "female", title: "Жінка" },
];

export const COMMUNICATION_METHODS = [
  { value: "byEmail", title: "Електронною поштою" },
  { value: "byPhone", title: "Телефоном" },
];

export const DOCUMENT_TYPES = [
  {
    value: "protectionCertificate",
    title: "Посвідчення особи, яка потребує додаткового захист",
  },
  { value: "passportNote", title: "Паспорт (книжечка)" },
  { value: "passportId", title: "Паспорт (ID-картка)" },
  {
    value: "permanentResidence",
    title: "Посвідка на постійне проживання в Україні",
  },
  {
    value: "temporaryResidence",
    title: "Посвідка на постійне проживання в Україні",
  },
  { value: "provisionalResidence", title: "Посвідка на проживання" },
  {
    value: "provisionalCitizenship",
    title: "Тимчасове посвідчення громадянина України",
  },
];
